---
# Documentation available at http://expeditor-docs.es.chef.io/
product_key: chef-server

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-server-notify

automate:
  organization: products
  project: chef-server

github:
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"
  # The Github Team primarily responsible for handling incoming Pull Requests.
  maintainer_group: chef/chef-server-maintainers

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:trigger_omnibus_build:
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
      only_if: built_in:bump_version
  - built_in:update_acc:
      only_if_labels:
        - "Expeditor: ACC Only"

# Subscription to workload action of pull request merge to master branch on
# omnibus-software project will allow us to trigger an uncached omnibus build
# for chef-server when the omnibus-software has modified software config files.
subscriptions:
  # chef/omnibus-software
  - workload: pull_request_merged:chef/omnibus-software:master:*
    actions:
      - built_in:trigger_omnibus_expcache_build:
          only_if_modified:
            - config/software/*
# These actions are taken, in the order specified, when an Omnibus artifact is promoted
# within Chef's internal artifact storage system.
#
# TODO: add promoted_to_unstable action to update changelog with modified omnibus components
artifact_actions:
  promoted_to_unstable:
    - built_in:update_acc
  promoted_to_current:
  promoted_to_stable:
    - built_in:rollover_changelog
    - built_in:notify_chefio_slack_channels
